const keys = ['select','selected','selectionTitle','verifying','verified','priceChanged','conditions','refund','change','allowed','notAllowed','selectionNote','back','retry','expired','verifyError'];
const rows = {
tr: 'Uçuşu seç|Seçildi · Detayları gör|Seçtiğin uçuş|Fiyat ve müsaitlik doğrulanıyor…|Uçuş seçildi. Güncel teklif doğrulandı.|Fiyat güncellendi|Bilet koşulları|İade|Değişiklik|Koşullara bağlı olarak mümkün|İzin verilmiyor|Bu seçim rezervasyon oluşturmaz. Ödeme ve biletleme henüz açık değil; satın alma sırasında fiyat yeniden doğrulanacaktır.|Sonuçlara dön|Tekrar dene|Bu teklifin süresi dolmuş veya artık mevcut değil. Sonuçlara dönüp yeniden uçuş ara.|Uçuş doğrulanamadı. Tekrar dene veya başka bir uçuş seç.',
en: 'Select flight|Selected · View details|Your selected flight|Verifying price and availability…|Flight selected. Current offer verified.|Price updated|Ticket conditions|Refunds|Changes|Available subject to conditions|Not permitted|Selection does not create a reservation. Payment and ticketing are not available yet; the price will be checked again at purchase.|Back to results|Try again|This offer has expired or is no longer available. Return to results and search again.|Could not verify this flight. Try again or select another flight.',
de: 'Flug auswählen|Ausgewählt · Details|Dein ausgewählter Flug|Preis und Verfügbarkeit werden geprüft…|Flug ausgewählt. Aktuelles Angebot bestätigt.|Preis aktualisiert|Ticketbedingungen|Erstattung|Änderungen|Unter Bedingungen möglich|Nicht erlaubt|Die Auswahl erstellt keine Buchung. Zahlung und Ticketausstellung sind noch nicht verfügbar; der Preis wird beim Kauf erneut geprüft.|Zurück zu Ergebnissen|Erneut versuchen|Angebot abgelaufen oder nicht mehr verfügbar. Bitte erneut suchen.|Flug konnte nicht geprüft werden. Erneut versuchen oder anderen Flug wählen.',
fr: 'Choisir ce vol|Sélectionné · Détails|Votre vol sélectionné|Vérification du prix et de la disponibilité…|Vol sélectionné. Offre actuelle vérifiée.|Prix actualisé|Conditions du billet|Remboursement|Modifications|Possible sous conditions|Non autorisé|La sélection ne crée pas de réservation. Paiement et émission de billets indisponibles pour le moment ; le prix sera revérifié lors de l’achat.|Retour aux résultats|Réessayer|Cette offre a expiré ou n’est plus disponible. Relancez une recherche.|Impossible de vérifier ce vol. Réessayez ou choisissez un autre vol.',
es: 'Seleccionar vuelo|Seleccionado · Detalles|Tu vuelo seleccionado|Verificando precio y disponibilidad…|Vuelo seleccionado. Oferta actual verificada.|Precio actualizado|Condiciones del billete|Reembolso|Cambios|Permitido bajo condiciones|No permitido|La selección no crea una reserva. El pago y la emisión aún no están disponibles; el precio se verificará al comprar.|Volver a resultados|Reintentar|Esta oferta ha caducado o ya no está disponible. Busca de nuevo.|No se pudo verificar el vuelo. Reintenta o selecciona otro.',
it: 'Seleziona volo|Selezionato · Dettagli|Il volo selezionato|Verifica di prezzo e disponibilità…|Volo selezionato. Offerta attuale verificata.|Prezzo aggiornato|Condizioni del biglietto|Rimborso|Modifiche|Possibile a determinate condizioni|Non consentito|La selezione non crea una prenotazione. Pagamento ed emissione non ancora disponibili; il prezzo sarà verificato all’acquisto.|Torna ai risultati|Riprova|Offerta scaduta o non più disponibile. Effettua una nuova ricerca.|Impossibile verificare il volo. Riprova o scegli un altro volo.',
pt: 'Selecionar voo|Selecionado · Detalhes|Seu voo selecionado|Verificando preço e disponibilidade…|Voo selecionado. Oferta atual verificada.|Preço atualizado|Condições da passagem|Reembolso|Alterações|Permitido sob condições|Não permitido|A seleção não cria uma reserva. Pagamento e emissão ainda indisponíveis; o preço será verificado na compra.|Voltar aos resultados|Tentar novamente|Esta oferta expirou ou não está mais disponível. Faça uma nova busca.|Não foi possível verificar o voo. Tente novamente ou escolha outro.',
ru: 'Выбрать рейс|Выбрано · Подробнее|Выбранный рейс|Проверяем цену и наличие…|Рейс выбран. Текущее предложение проверено.|Цена обновлена|Условия билета|Возврат|Изменения|Возможно при соблюдении условий|Не разрешено|Выбор не создаёт бронирование. Оплата и выписка билетов пока недоступны; цена будет проверена при покупке.|К результатам|Повторить|Предложение истекло или недоступно. Выполните поиск заново.|Не удалось проверить рейс. Повторите попытку или выберите другой.',
ar: 'اختر الرحلة|تم الاختيار · التفاصيل|رحلتك المختارة|جارٍ التحقق من السعر والتوفر…|تم اختيار الرحلة والتحقق من العرض الحالي.|تم تحديث السعر|شروط التذكرة|الاسترداد|التغييرات|متاح وفق الشروط|غير مسموح|الاختيار لا ينشئ حجزاً. الدفع وإصدار التذاكر غير متاحين بعد؛ سيتم التحقق من السعر عند الشراء.|العودة للنتائج|حاول مجدداً|انتهت صلاحية العرض أو لم يعد متاحاً. ابحث مجدداً.|تعذر التحقق من الرحلة. حاول مجدداً أو اختر رحلة أخرى.',
zh: '选择航班|已选择 · 查看详情|你选择的航班|正在核实价格和余票…|航班已选择，当前报价已核实。|价格已更新|机票条款|退票|改签|符合条件时可办理|不允许|选择航班不会创建预订。目前尚不支持支付和出票，购买时将再次核实价格。|返回结果|重试|此报价已过期或不再可用，请重新搜索。|无法核实航班，请重试或选择其他航班。',
};
export default Object.fromEntries(Object.entries(rows).map(([language, row]) => [language, Object.fromEntries(keys.map((key, index) => [key, row.split('|')[index]]))]));
