const keys = ['select', 'selected', 'selectionTitle', 'verifying', 'verified', 'priceChanged', 'conditions', 'refund', 'change', 'allowed', 'notAllowed', 'back', 'retry', 'expired', 'verifyError'];
const rows = {
tr: 'Uçuşu seç|Seçildi · Detayları gör|Seçtiğin uçuş|Fiyat ve müsaitlik doğrulanıyor…|Uçuş seçildi. Güncel teklif doğrulandı.|Fiyat güncellendi|Bilet koşulları|İade|Değişiklik|Koşullara bağlı olarak mümkün|İzin verilmiyor|Sonuçlara dön|Tekrar dene|Bu teklifin süresi dolmuş veya artık mevcut değil. Sonuçlara dönüp yeniden uçuş ara.|Uçuş doğrulanamadı. Tekrar dene veya başka bir uçuş seç.',
en: 'Select flight|Selected · View details|Your selected flight|Verifying price and availability…|Flight selected. Current offer verified.|Price updated|Ticket conditions|Refunds|Changes|Available subject to conditions|Not permitted|Back to results|Try again|This offer has expired or is no longer available. Return to results and search again.|Could not verify this flight. Try again or select another flight.',
de: 'Flug auswählen|Ausgewählt · Details|Dein ausgewählter Flug|Preis und Verfügbarkeit werden geprüft…|Flug ausgewählt. Aktuelles Angebot bestätigt.|Preis aktualisiert|Ticketbedingungen|Erstattung|Änderungen|Unter Bedingungen möglich|Nicht erlaubt|Zurück zu Ergebnissen|Erneut versuchen|Angebot abgelaufen oder nicht mehr verfügbar. Bitte erneut suchen.|Flug konnte nicht geprüft werden. Erneut versuchen oder anderen Flug wählen.',
fr: 'Choisir ce vol|Sélectionné · Détails|Votre vol sélectionné|Vérification du prix et de la disponibilité…|Vol sélectionné. Offre actuelle vérifiée.|Prix actualisé|Conditions du billet|Remboursement|Modifications|Possible sous conditions|Non autorisé|Retour aux résultats|Réessayer|Cette offre a expiré ou n’est plus disponible. Relancez une recherche.|Impossible de vérifier ce vol. Réessayez ou choisissez un autre vol.',
es: 'Seleccionar vuelo|Seleccionado · Detalles|Tu vuelo seleccionado|Verificando precio y disponibilidad…|Vuelo seleccionado. Oferta actual verificada.|Precio actualizado|Condiciones del billete|Reembolso|Cambios|Permitido bajo condiciones|No permitido|Volver a resultados|Reintentar|Esta oferta ha caducado o ya no está disponible. Busca de nuevo.|No se pudo verificar el vuelo. Reintenta o selecciona otro.',
it: 'Seleziona volo|Selezionato · Dettagli|Il volo selezionato|Verifica di prezzo e disponibilità…|Volo selezionato. Offerta attuale verificata.|Prezzo aggiornato|Condizioni del biglietto|Rimborso|Modifiche|Possibile a determinate condizioni|Non consentito|Torna ai risultati|Riprova|Offerta scaduta o non più disponibile. Effettua una nuova ricerca.|Impossibile verificare il volo. Riprova o scegli un altro volo.',
pt: 'Selecionar voo|Selecionado · Detalhes|Seu voo selecionado|Verificando preço e disponibilidade…|Voo selecionado. Oferta atual verificada.|Preço atualizado|Condições da passagem|Reembolso|Alterações|Permitido sob condições|Não permitido|Voltar aos resultados|Tentar novamente|Esta oferta expirou ou não está mais disponível. Faça uma nova busca.|Não foi possível verificar o voo. Tente novamente ou escolha outro.',
ru: 'Выбрать рейс|Выбрано · Подробнее|Выбранный рейс|Проверяем цену и наличие…|Рейс выбран. Текущее предложение проверено.|Цена обновлена|Условия билета|Возврат|Изменения|Возможно при соблюдении условий|Не разрешено|К результатам|Повторить|Предложение истекло или недоступно. Выполните поиск заново.|Не удалось проверить рейс. Повторите попытку или выберите другой.',
ar: 'اختر الرحلة|تم الاختيار · التفاصيل|رحلتك المختارة|جارٍ التحقق من السعر والتوفر…|تم اختيار الرحلة والتحقق من العرض الحالي.|تم تحديث السعر|شروط التذكرة|الاسترداد|التغييرات|متاح وفق الشروط|غير مسموح|العودة للنتائج|حاول مجدداً|انتهت صلاحية العرض أو لم يعد متاحاً. ابحث مجدداً.|تعذر التحقق من الرحلة. حاول مجدداً أو اختر رحلة أخرى.',
zh: '选择航班|已选择 · 查看详情|你选择的航班|正在核实价格和余票…|航班已选择，当前报价已核实。|价格已更新|机票条款|退票|改签|符合条件时可办理|不允许|返回结果|重试|此报价已过期或不再可用，请重新搜索。|无法核实航班，请重试或选择其他航班。',
};
export default Object.fromEntries(Object.entries(rows).map(([language, row]) => [language, Object.fromEntries(keys.map((key, index) => [key, row.split('|')[index]]))]));
