const homeTravelTranslations = {
  en:{eyebrow:"ROTAVOY TRAVEL",title:"Your next stay starts here",text:"Search live hotel availability and total stay prices without leaving Rotavoy.",destination:"Destination",destinationPlaceholder:"City or destination",checkin:"Check-in",checkout:"Check-out",guests:"Guests",guest1:"1 guest",guestsCount:"guests",search:"Search hotels",feature1:"Live availability",feature2:"Total stay prices",feature3:"Book on Rotavoy",badge:"HOTELS & HOLIDAYS"},
  tr:{eyebrow:"ROTAVOY TRAVEL",title:"Sıradaki konaklaman burada başlıyor",text:"Rotavoy’dan ayrılmadan canlı otel müsaitliğini ve toplam konaklama fiyatlarını ara.",destination:"Destinasyon",destinationPlaceholder:"Şehir veya tatil bölgesi",checkin:"Giriş",checkout:"Çıkış",guests:"Misafir",guest1:"1 misafir",guestsCount:"misafir",search:"Otel ara",feature1:"Canlı müsaitlik",feature2:"Toplam konaklama fiyatı",feature3:"Rotavoy’da rezervasyon",badge:"OTELLER & TATİL"},
  ru:{eyebrow:"ROTAVOY TRAVEL",title:"Ваше следующее путешествие начинается здесь",text:"Ищите актуальные номера и полную стоимость проживания прямо на Rotavoy.",destination:"Направление",destinationPlaceholder:"Город или курорт",checkin:"Заезд",checkout:"Выезд",guests:"Гости",guest1:"1 гость",guestsCount:"гостей",search:"Найти отели",feature1:"Актуальная доступность",feature2:"Полная стоимость",feature3:"Бронирование на Rotavoy",badge:"ОТЕЛИ И ОТДЫХ"},
  ar:{eyebrow:"ROTAVOY TRAVEL",title:"إقامتك القادمة تبدأ هنا",text:"ابحث عن توفر الفنادق والأسعار الإجمالية مباشرة على Rotavoy.",destination:"الوجهة",destinationPlaceholder:"مدينة أو وجهة",checkin:"الدخول",checkout:"الخروج",guests:"الضيوف",guest1:"ضيف واحد",guestsCount:"ضيوف",search:"ابحث عن فندق",feature1:"توفر مباشر",feature2:"السعر الإجمالي",feature3:"الحجز على Rotavoy",badge:"فنادق وعطلات"},
  zh:{eyebrow:"ROTAVOY TRAVEL",title:"下一次住宿从这里开始",text:"无需离开 Rotavoy，即可查询实时房态和住宿总价。",destination:"目的地",destinationPlaceholder:"城市或度假地",checkin:"入住",checkout:"退房",guests:"住客",guest1:"1 位住客",guestsCount:"位住客",search:"搜索酒店",feature1:"实时房态",feature2:"住宿总价",feature3:"在 Rotavoy 预订",badge:"酒店与度假"},
  es:{eyebrow:"ROTAVOY TRAVEL",title:"Tu próxima estancia comienza aquí",text:"Busca disponibilidad y precios totales de hoteles sin salir de Rotavoy.",destination:"Destino",destinationPlaceholder:"Ciudad o destino",checkin:"Entrada",checkout:"Salida",guests:"Huéspedes",guest1:"1 huésped",guestsCount:"huéspedes",search:"Buscar hoteles",feature1:"Disponibilidad en vivo",feature2:"Precio total",feature3:"Reserva en Rotavoy",badge:"HOTELES Y VACACIONES"},
  pt:{eyebrow:"ROTAVOY TRAVEL",title:"Sua próxima estadia começa aqui",text:"Pesquise disponibilidade e preços totais sem sair da Rotavoy.",destination:"Destino",destinationPlaceholder:"Cidade ou destino",checkin:"Entrada",checkout:"Saída",guests:"Hóspedes",guest1:"1 hóspede",guestsCount:"hóspedes",search:"Buscar hotéis",feature1:"Disponibilidade ao vivo",feature2:"Preço total",feature3:"Reserva na Rotavoy",badge:"HOTÉIS E FÉRIAS"},
  fr:{eyebrow:"ROTAVOY TRAVEL",title:"Votre prochain séjour commence ici",text:"Recherchez les disponibilités et le prix total sans quitter Rotavoy.",destination:"Destination",destinationPlaceholder:"Ville ou destination",checkin:"Arrivée",checkout:"Départ",guests:"Voyageurs",guest1:"1 voyageur",guestsCount:"voyageurs",search:"Rechercher",feature1:"Disponibilité en direct",feature2:"Prix total",feature3:"Réservation sur Rotavoy",badge:"HÔTELS ET VACANCES"},
  de:{eyebrow:"ROTAVOY TRAVEL",title:"Ihr nächster Aufenthalt beginnt hier",text:"Prüfen Sie Verfügbarkeit und Gesamtpreise direkt bei Rotavoy.",destination:"Reiseziel",destinationPlaceholder:"Stadt oder Reiseziel",checkin:"Anreise",checkout:"Abreise",guests:"Gäste",guest1:"1 Gast",guestsCount:"Gäste",search:"Hotels suchen",feature1:"Live-Verfügbarkeit",feature2:"Gesamtpreis",feature3:"Buchung bei Rotavoy",badge:"HOTELS & URLAUB"},
  it:{eyebrow:"ROTAVOY TRAVEL",title:"Il tuo prossimo soggiorno inizia qui",text:"Cerca disponibilità e prezzi totali senza lasciare Rotavoy.",destination:"Destinazione",destinationPlaceholder:"Città o destinazione",checkin:"Arrivo",checkout:"Partenza",guests:"Ospiti",guest1:"1 ospite",guestsCount:"ospiti",search:"Cerca hotel",feature1:"Disponibilità in tempo reale",feature2:"Prezzo totale",feature3:"Prenotazione su Rotavoy",badge:"HOTEL E VACANZE"}
};

export default homeTravelTranslations;
