const fields = ['details','unknownMeal','nonRefundable','refundable','unknownCancellation','freeUntil','penalty','included','extra','unknownTax','after','charge','unknownPenalty','now','updated','priceChanged','cancellationChanged','mealChanged','chargesChanged','roomChanged','conditionsChanged','accept','select','selected','roomOnly','breakfast','halfBoard','fullBoard','allInclusive','dinner','lunch','breakfastDinner','breakfastLunch','lunchDinner'];
const rows = {
  en: ['Price and cancellation details','Meal plan confirmed before payment','Non-refundable','Refundable · see conditions','Cancellation conditions confirmed before payment','Free cancellation until','Cancellation charges apply','Taxes and fees included','Pay separately at the property','Tax details confirmed before payment','From','Cancellation charge','See cancellation conditions','Payment is collected now','Reservation conditions updated','Price updated','Cancellation conditions updated','Meal plan updated','Taxes or fees updated','Room details updated','Booking conditions updated','I accept the current price and reservation conditions','Select this room','Selected','Room only','Breakfast included','Half board','Full board','All inclusive','Dinner included','Lunch included','Breakfast and dinner included','Breakfast and lunch included','Lunch and dinner included'],
  tr: ['Fiyat ve iptal detayları','Yemek planı ödeme öncesinde doğrulanır','İade edilemez','İade edilebilir · koşulları incele','İptal koşulları ödeme öncesinde doğrulanır','Ücretsiz iptal için son tarih','İptalde ücret uygulanır','Vergiler ve ücretler dahil','Tesiste ayrıca ödenecek','Vergi detayları ödeme öncesinde doğrulanır','Bu tarihten itibaren','İptal ücreti','İptal koşullarını incele','Ödeme şimdi alınır','Rezervasyon koşulları güncellendi','Fiyat güncellendi','İptal koşulları güncellendi','Yemek planı güncellendi','Vergi veya ücretler güncellendi','Oda bilgileri güncellendi','Rezervasyon koşulları güncellendi','Güncel fiyatı ve rezervasyon koşullarını kabul ediyorum','Bu odayı seç','Seçildi','Sadece Oda','Kahvaltı Dahil','Yarım Pansiyon','Tam Pansiyon','Her Şey Dahil','Akşam Yemeği Dahil','Öğle Yemeği Dahil','Kahvaltı ve Akşam Yemeği Dahil','Kahvaltı ve Öğle Yemeği Dahil','Öğle ve Akşam Yemeği Dahil'],
  de: ['Preis- und Stornierungsdetails','Verpflegung wird vor Zahlung bestätigt','Nicht erstattbar','Erstattbar · Bedingungen ansehen','Stornobedingungen werden vor Zahlung bestätigt','Kostenlose Stornierung bis','Stornogebühren fallen an','Steuern und Gebühren inklusive','Separat in der Unterkunft zu zahlen','Steuerdetails werden vor Zahlung bestätigt','Ab','Stornogebühr','Stornobedingungen ansehen','Zahlung erfolgt jetzt','Buchungsbedingungen aktualisiert','Preis aktualisiert','Stornobedingungen aktualisiert','Verpflegung aktualisiert','Steuern oder Gebühren aktualisiert','Zimmerdetails aktualisiert','Buchungsbedingungen aktualisiert','Ich akzeptiere den aktuellen Preis und die Buchungsbedingungen','Dieses Zimmer wählen','Ausgewählt','Nur Zimmer','Frühstück inklusive','Halbpension','Vollpension','All inclusive','Abendessen inklusive','Mittagessen inklusive','Frühstück und Abendessen inklusive','Frühstück und Mittagessen inklusive','Mittag- und Abendessen inklusive'],
  fr: ['Détails du prix et de l’annulation','Repas confirmés avant le paiement','Non remboursable','Remboursable · voir les conditions','Conditions d’annulation confirmées avant paiement','Annulation gratuite jusqu’au','Frais d’annulation applicables','Taxes et frais inclus','À payer séparément sur place','Taxes confirmées avant paiement','À partir du','Frais d’annulation','Voir les conditions d’annulation','Paiement immédiat','Conditions de réservation mises à jour','Prix mis à jour','Annulation mise à jour','Repas mis à jour','Taxes ou frais mis à jour','Chambre mise à jour','Conditions mises à jour','J’accepte le prix actuel et les conditions de réservation','Choisir cette chambre','Sélectionnée','Chambre seule','Petit-déjeuner inclus','Demi-pension','Pension complète','Tout compris','Dîner inclus','Déjeuner inclus','Petit-déjeuner et dîner inclus','Petit-déjeuner et déjeuner inclus','Déjeuner et dîner inclus'],
  es: ['Detalles de precio y cancelación','Comidas confirmadas antes del pago','No reembolsable','Reembolsable · ver condiciones','Cancelación confirmada antes del pago','Cancelación gratuita hasta','Se aplican cargos de cancelación','Impuestos y cargos incluidos','Pago adicional en el alojamiento','Impuestos confirmados antes del pago','Desde','Cargo de cancelación','Ver condiciones de cancelación','Pago inmediato','Condiciones de reserva actualizadas','Precio actualizado','Cancelación actualizada','Comidas actualizadas','Impuestos o cargos actualizados','Habitación actualizada','Condiciones actualizadas','Acepto el precio actual y las condiciones de reserva','Elegir esta habitación','Seleccionada','Solo habitación','Desayuno incluido','Media pensión','Pensión completa','Todo incluido','Cena incluida','Almuerzo incluido','Desayuno y cena incluidos','Desayuno y almuerzo incluidos','Almuerzo y cena incluidos'],
  it: ['Dettagli prezzo e cancellazione','Pasti confermati prima del pagamento','Non rimborsabile','Rimborsabile · vedi condizioni','Cancellazione confermata prima del pagamento','Cancellazione gratuita fino al','Si applicano penali di cancellazione','Tasse e costi inclusi','Da pagare separatamente in struttura','Tasse confermate prima del pagamento','Dal','Penale di cancellazione','Vedi condizioni di cancellazione','Pagamento immediato','Condizioni di prenotazione aggiornate','Prezzo aggiornato','Cancellazione aggiornata','Pasti aggiornati','Tasse o costi aggiornati','Camera aggiornata','Condizioni aggiornate','Accetto il prezzo attuale e le condizioni di prenotazione','Scegli questa camera','Selezionata','Solo camera','Colazione inclusa','Mezza pensione','Pensione completa','Tutto incluso','Cena inclusa','Pranzo incluso','Colazione e cena incluse','Colazione e pranzo inclusi','Pranzo e cena inclusi'],
  pt: ['Detalhes do preço e cancelamento','Refeições confirmadas antes do pagamento','Não reembolsável','Reembolsável · ver condições','Cancelamento confirmado antes do pagamento','Cancelamento gratuito até','Aplicam-se taxas de cancelamento','Impostos e taxas incluídos','Pagamento adicional na propriedade','Impostos confirmados antes do pagamento','A partir de','Taxa de cancelamento','Ver condições de cancelamento','Pagamento imediato','Condições de reserva atualizadas','Preço atualizado','Cancelamento atualizado','Refeições atualizadas','Impostos ou taxas atualizados','Quarto atualizado','Condições atualizadas','Aceito o preço atual e as condições de reserva','Escolher este quarto','Selecionado','Só quarto','Café da manhã incluído','Meia pensão','Pensão completa','Tudo incluído','Jantar incluído','Almoço incluído','Café da manhã e jantar incluídos','Café da manhã e almoço incluídos','Almoço e jantar incluídos'],
  ru: ['Цена и условия отмены','Питание подтверждается до оплаты','Без возврата','С возвратом · см. условия','Условия отмены подтверждаются до оплаты','Бесплатная отмена до','При отмене взимается сбор','Налоги и сборы включены','Доплата в объекте размещения','Налоги подтверждаются до оплаты','С','Сбор за отмену','См. условия отмены','Оплата сейчас','Условия бронирования обновлены','Цена обновлена','Условия отмены обновлены','Питание обновлено','Налоги или сборы обновлены','Номер обновлён','Условия обновлены','Я принимаю текущую цену и условия бронирования','Выбрать номер','Выбран','Без питания','Завтрак включён','Полупансион','Полный пансион','Всё включено','Ужин включён','Обед включён','Завтрак и ужин включены','Завтрак и обед включены','Обед и ужин включены'],
  ar: ['تفاصيل السعر والإلغاء','تأكيد الوجبات قبل الدفع','غير قابل للاسترداد','قابل للاسترداد · راجع الشروط','تأكيد شروط الإلغاء قبل الدفع','إلغاء مجاني حتى','تطبق رسوم الإلغاء','الضرائب والرسوم مشمولة','دفع إضافي في مكان الإقامة','تأكيد الضرائب قبل الدفع','اعتباراً من','رسوم الإلغاء','راجع شروط الإلغاء','الدفع الآن','تم تحديث شروط الحجز','تم تحديث السعر','تم تحديث شروط الإلغاء','تم تحديث الوجبات','تم تحديث الضرائب أو الرسوم','تم تحديث الغرفة','تم تحديث الشروط','أوافق على السعر الحالي وشروط الحجز','اختر هذه الغرفة','محددة','غرفة فقط','الإفطار مشمول','نصف إقامة','إقامة كاملة','شامل كلياً','العشاء مشمول','الغداء مشمول','الإفطار والعشاء مشمولان','الإفطار والغداء مشمولان','الغداء والعشاء مشمولان'],
  zh: ['价格和取消详情','付款前确认餐食计划','不可退款','可退款 · 查看条款','付款前确认取消条款','免费取消截止时间','取消将收取费用','含税费','需在住宿处另付','付款前确认税费','自','取消费用','查看取消条款','现在付款','预订条款已更新','价格已更新','取消条款已更新','餐食已更新','税费已更新','客房已更新','条款已更新','我接受当前价格和预订条款','选择此客房','已选择','仅客房','含早餐','半食宿','全食宿','全包','含晚餐','含午餐','含早餐和晚餐','含早餐和午餐','含午餐和晚餐'],
};
const missing = {
  en: ['Meal plan not provided', 'Cancellation information not provided', 'Tax breakdown not provided', 'Amount not provided'],
  tr: ['Yemek planı belirtilmedi', 'İptal bilgisi sağlanmadı', 'Vergi dökümü sağlanmadı', 'Tutar belirtilmedi'],
  de: ['Verpflegung nicht angegeben', 'Stornoinformationen nicht angegeben', 'Steueraufschlüsselung nicht angegeben', 'Betrag nicht angegeben'],
  fr: ['Repas non précisés', 'Annulation non précisée', 'Détail des taxes non fourni', 'Montant non précisé'],
  es: ['Comidas no especificadas', 'Cancelación no especificada', 'Desglose de impuestos no facilitado', 'Importe no especificado'],
  it: ['Pasti non specificati', 'Cancellazione non specificata', 'Dettaglio tasse non fornito', 'Importo non specificato'],
  pt: ['Refeições não informadas', 'Cancelamento não informado', 'Detalhes dos impostos não fornecidos', 'Valor não informado'],
  ru: ['Питание не указано', 'Информация об отмене не указана', 'Сведения о налогах не предоставлены', 'Сумма не указана'],
  ar: ['الوجبات غير محددة', 'معلومات الإلغاء غير متوفرة', 'تفاصيل الضرائب غير متوفرة', 'المبلغ غير محدد'],
  zh: ['未提供餐食计划', '未提供取消信息', '未提供税费明细', '未提供金额'],
};
export default Object.fromEntries(Object.entries(rows).map(([language, values]) => [language, {
  ...Object.fromEntries(fields.map((key, index) => [key, values[index]])),
  ...Object.fromEntries(['unknownMeal', 'unknownCancellation', 'unknownTax', 'unknownAmount'].map((key, index) => [key, missing[language][index]])),
}]));
