import { useEffect, useState } from 'react';
import { adminRequest, downloadAdminCsv } from '../../services/adminApi';
export const eventLabels = { hotel_open: 'Oteli açtı', page_view: 'Sayfa görüntüledi', hotel_view: 'Oteli görüntüledi', hotel_search: 'Otel aradı', hotel_select: 'Oteli seçti', room_select: 'Odayı seçti', flight_search: 'Uçuş aradı', flight_view: 'Uçuşu inceledi', flight_select: 'Uçuşu seçti', category_select: 'Kategori değiştirdi', checkout_view: 'Ödemeye geçti', car_plan: 'Araç planladı', activity_plan: 'Aktivite planladı' };
const date = value => new Date(value).toLocaleString('tr-TR');
function detail(item) {
  const d = item.details || {};
  return [d.hotelName || d.hotelId, d.origin ? `${d.originName || d.origin} (${d.origin}) → ${d.destinationName || d.destination} (${d.destination})` : d.destination, d.roomName, d.category, d.checkin && `${d.checkin} → ${d.checkout}`, d.departure && `${d.departure}${d.returnDate ? ` → ${d.returnDate}` : ''}`, d.adults && `${d.adults} yetişkin`, d.children && `${d.children} çocuk`, d.offerId].filter(Boolean).join(' · ');
}
function TrackingStatus({ refresh }) {
  let value = null;
  try { value = JSON.parse(localStorage.getItem('rotavoy_analytics_status_v1') || 'null'); } catch { /* No local tracking yet. */ }
  return <p className={value?.lastError ? 'adminError' : 'adminHint'} key={refresh}>Bu tarayıcıda son başarılı analitik gönderimi: {value?.lastSuccess ? date(value.lastSuccess) : 'Henüz yok'}.{value?.pending ? ` Bekleyen ${value.pending} olay var.` : ''}{value?.lastError ? ` Son hata: ${value.lastError}. Bağlantı düzeldiğinde yeniden denenecek.` : ''}</p>;
}
export default function TravelAnalyticsPanel({ refreshKey = 0 }) {
  const [days, setDays] = useState('7'); const [type, setType] = useState(''); const [bots, setBots] = useState('');
  const [query, setQuery] = useState(''); const [search, setSearch] = useState(''); const [visitor, setVisitor] = useState('');
  const [page, setPage] = useState(1); const [refresh, setRefresh] = useState(0); const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    const params = new URLSearchParams({ days, type, bots, q: search, visitorId: visitor, page: String(page), limit: '50' });
    adminRequest(`/analytics?${params}`, { signal: controller.signal }).then(setData).catch(err => { if (err.name !== 'AbortError') setError(err.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [days, type, bots, search, visitor, page, refresh, refreshKey]);
  useEffect(() => { const timer = setInterval(() => setRefresh(value => value + 1), 30000); return () => clearInterval(timer); }, []);
  const summary = data?.summary || {}; const types = summary.types || [];
  function change(setter, value) { setter(value); setPage(1); }
  return <section><TrackingStatus refresh={refresh + refreshKey} /><p className="adminHint">Giriş yapan hesaplar hesap bilgisiyle; diğerleri anonim ziyaretçi numarasıyla görünür. IP konumu yaklaşık olup yerel bağlantıda boş olabilir. Loglar 30 saniyede yenilenir. Ölçüm bu özelliğin kurulmasıyla başlar.</p>
    <div className="adminToolbar"><form onSubmit={event => { event.preventDefault(); change(setSearch, query); }}><label>İsim, IP, şehir, otel veya rota<input value={query} maxLength="100" onChange={event => setQuery(event.target.value)} /></label><button>Ara</button></form><label>Dönem<select value={days} onChange={event => change(setDays, event.target.value)}>{[['1','Son 24 saat'],['7','Son 7 gün'],['30','Son 30 gün'],['90','Son 90 gün'],['365','Son 1 yıl']].map(([key,title]) => <option key={key} value={key}>{title}</option>)}</select></label><label>Olay<select value={type} onChange={event => change(setType, event.target.value)}><option value="">Tümü</option>{Object.entries(eventLabels).map(([key,title]) => <option key={key} value={key}>{title}</option>)}</select></label><label>Trafik<select value={bots} onChange={event => change(setBots, event.target.value)}><option value="">Tümü</option><option value="exclude">Belirgin botları gizle</option></select></label><button onClick={() => setRefresh(value => value + 1)}>Yenile</button><button disabled={!data?.items?.length || loading} onClick={() => downloadAdminCsv(data.items.map(item => ({ tarih: item.createdAt, ziyaretci: item.visitorId, oturum: item.sessionId, hesap: item.identity, ip: item.ip, ulke: item.country, sehir: item.city, cihaz: item.device, kaynak: item.source, olay: eventLabels[item.type], sayfa: item.path, detay: detail(item) })), 'rotavoy-analitik.csv')}>Bu sayfayı CSV indir</button></div>
    {visitor && <p className="adminHint">Ziyaretçi: {visitor} <button onClick={() => change(setVisitor, '')}>Tüm ziyaretçiler</button></p>}
    {error && <p className="adminError" role="alert">{error}</p>}{loading && <p role="status">Analitik yükleniyor…</p>}
    {data && <><div className="adminMetricGrid">{[['Tekil ziyaretçi', summary.visitors?.[0]?.count || 0], ['Oturum', summary.sessions?.[0]?.count || 0], ['Sayfa görüntüleme', types.find(item => item._id === 'page_view')?.count || 0], ['Toplam olay', data.total]].map(([title,count]) => <article className="adminMetric" key={title}><span>{title}</span><strong>{count}</strong></article>)}</div>
    <div className="adminIntegrationGrid">{[['Konumlar', summary.locations || [], item => [item._id.city, item._id.country].filter(Boolean).join(' / ') || 'Konum bilinmiyor'], ['Kaynaklar', summary.sources || [], item => item._id || 'direct'], ['İncelenen oteller', summary.hotels || [], item => item.name || item._id]].map(([title,items,name]) => <section className="adminPanel" key={title}><h2>{title}</h2>{items.map((item,index) => <p key={index} className="adminSummaryLine"><span>{name(item)}</span><strong>{item.count}</strong></p>)}{!items.length && <p>Henüz kayıt yok.</p>}</section>)}</div>
    <h2>Ziyaret ve davranış logları</h2><div className="adminTableWrap"><table><thead><tr><th>Zaman / oturum</th><th>Ziyaretçi</th><th>Konum / cihaz</th><th>Kaynak</th><th>Olay / sayfa</th><th>Detay</th></tr></thead><tbody>{data.items.map(item => <tr key={item._id}><td>{date(item.createdAt)}<small>{item.sessionId?.slice(0,8)}</small></td><td><button onClick={() => change(setVisitor, item.visitorId)}>{item.identity || `Anonim ${item.visitorId.slice(0,8)}`}</button><small>{item.ip}</small>{item.bot && <small>Olası bot</small>}</td><td>{[item.city,item.country].filter(Boolean).join(' / ') || 'Bilinmiyor'}<small>{item.device} · {item.browser}</small></td><td>{item.source || 'direct'}<small>{item.referrer}</small></td><td>{eventLabels[item.type] || item.type}<small>{item.path}</small></td><td>{detail(item) || '—'}</td></tr>)}</tbody></table></div>{!data.items.length && <p className="adminEmpty">Bu filtrelerde henüz ziyaret kaydı yok.</p>}
    <div className="adminPagination"><span>{data.total} olay · Sayfa {page} / {Math.max(1, Math.ceil(data.total / data.limit))}</span><button disabled={loading || page <= 1} onClick={() => setPage(value => value - 1)}>Önceki</button><button disabled={loading || page * data.limit >= data.total} onClick={() => setPage(value => value + 1)}>Sonraki</button></div></>}
  </section>;
}
