import { useEffect, useState } from 'react';
import { adminRequest, downloadAdminCsv } from '../../services/adminApi';
import './TravelAnalyticsPanel.css';
export const eventLabels = { hotel_open: 'Oteli açtı', page_view: 'Sayfa görüntüledi', hotel_view: 'Oteli inceledi', hotel_search: 'Otel aradı', hotel_select: 'Oteli seçti', room_select: 'Odayı seçti', flight_search: 'Uçuş aradı', flight_view: 'Uçuşu inceledi', flight_select: 'Uçuşu seçti', category_select: 'Kategori değiştirdi', checkout_view: 'Misafir bilgilerine geçti', payment_start: 'Ödemeyi başlattı', payment_ready: 'Ödeme ekranı hazır', payment_error: 'Ödeme adımında hata', booking_confirmation_view: 'Rezervasyon onayını gördü', booking_confirmed: 'Doğrulanmış rezervasyon', car_plan: 'Araç planladı', activity_plan: 'Aktivite planladı', heartbeat: 'Sitede aktif' };
const trafficLabels = { visitor: 'Standart ziyaretçi', admin: 'Doğrulanmış yönetici', test: 'Doğrulanmış test', suspected_bot: 'Şüpheli bot', unknown: 'Belirsiz', all: 'Tüm trafik' };
const date = value => new Date(value).toLocaleString('tr-TR');
const reasons = { signed_context_v2: 'Sunucu imzalı oturum', automation_user_agent: 'Tarayıcı otomasyon sinyali', invalid_or_expired_context: 'Geçersiz / süresi dolmuş işaret', no_exclusion_signal: 'Dışlama sinyali bulunmadı', legacy_client: 'Önceki istemci: doğrulama kanıtı yok', missing_booking_attribution: 'Ödeme oturumuna ait sınıflandırma kanıtı yok' };
function detail(item) {
  const d = item.details || {};
  return [d.hotelName || d.hotelId, d.origin ? `${d.origin} → ${d.destination}` : d.destination, d.roomName, d.checkin && `${d.checkin} → ${d.checkout}`, d.departure, d.paymentMethod].filter(Boolean).join(' · ');
}
function Breakdown({ title, items = [], label = item => item._id || 'Bilinmiyor', unit = 'ziyaretçi' }) {
  const max = Math.max(1, ...items.map(item => item.count));
  return <section className="avPanel"><h3>{title}<small>{unit}</small></h3>{items.length ? items.map((item, i) => <div className="avDistribution" key={i}><span>{label(item)}</span><b>{item.count}</b><div><i style={{ width: `${item.count / max * 100}%` }} /></div></div>) : <p className="adminHint">Bu aralıkta kayıt yok.</p>}</section>;
}
function Trend({ items = [], from, to }) {
  const map = new Map(items.map(item => [item._id, item.count]));
  const points = [];
  if (from && to) for (let time = +new Date(from.slice(0, 10)); time <= +new Date(to.slice(0, 10)); time += 86400000) { const day = new Date(time).toISOString().slice(0, 10); points.push({ day, count: map.get(day) || 0 }); }
  const max = Math.max(1, ...points.map(p => p.count));
  const xy = points.map((p, i) => `${20 + i * 660 / Math.max(1, points.length - 1)},${150 - p.count / max * 120}`).join(' ');
  return <section className="avPanel avTrend"><h3>Günlük trafik<small>Tekil ziyaretçi · UTC</small></h3><svg viewBox="0 0 700 180" role="img" aria-label={`Günlük tekil ziyaretçiler: ${points.map(p => `${p.day}: ${p.count}`).join(', ')}`}><path d="M20 30 H680 M20 90 H680 M20 150 H680" className="avGrid" /><polyline points={xy} fill="none" stroke="var(--admin-accent)" strokeWidth="3" />{points.map((p, i) => <circle key={p.day} cx={20 + i * 660 / Math.max(1, points.length - 1)} cy={150 - p.count / max * 120} r="3" fill="var(--admin-accent)"><title>{p.day}: {p.count}</title></circle>)}</svg><div className="avBetween"><small>{points[0]?.day}</small><small>{points.at(-1)?.day}</small></div><details><summary>Grafik verilerini göster</summary><div className="avChartData">{points.map(p => <span key={p.day}>{p.day}: <b>{p.count}</b></span>)}</div></details></section>;
}
function Journey({ visitorId, filters, refresh }) {
  const [page, setPage] = useState(1), [data, setData] = useState(null), [error, setError] = useState('');
  useEffect(() => {
    const controller = new AbortController(); setError(''); setData(null);
    adminRequest(`/analytics/v2?${new URLSearchParams({ ...filters, visitorId, page: String(page), limit: '25' })}`, { signal: controller.signal }).then(setData).catch(e => { if (e.name !== 'AbortError') setError(e.message); });
    return () => controller.abort();
  }, [visitorId, filters, page, refresh]);
  return <div className="avJourney">{error && <p role="alert">{error}</p>}{!data && !error && <p role="status">Hareketler yükleniyor…</p>}{data && <><ol>{data.journey?.map(item => <li key={item._id}><div><time>{date(item.createdAt)}</time><span className="adminBadge">{trafficLabels[item.trafficType]}</span></div><strong>{eventLabels[item.type] || item.type}</strong><p>{detail(item) || item.path}</p><small>Oturum {item.sessionId?.slice(0, 8)} · {item.source || 'direct'} · {reasons[item.classificationReason] || 'Geçmiş kayıt: doğrulama kanıtı yok'}</small></li>)}</ol>{!data.journey?.length && <p>Bu filtrelerde hareket yok.</p>}<div className="adminPagination"><span>Sayfa {page} · {data.totals.sessions} oturum · {data.totals.events} hareket</span><button disabled={page === 1} onClick={() => setPage(p => p - 1)}>Önceki hareketler</button><button disabled={page * 25 >= data.totals.events} onClick={() => setPage(p => p + 1)}>Sonraki hareketler</button><button disabled={!data.journey?.length} onClick={() => downloadAdminCsv(data.journey.map(item => ({ zaman: item.createdAt, oturum: item.sessionId, hareket: eventLabels[item.type], detay: detail(item), trafik: item.trafficType })), 'rotavoy-ziyaretci-hareketleri.csv')}>Hareketleri CSV indir</button></div></>}</div>;
}
const initial = { days: '7', from: '', to: '', country: '', source: '', traffic: 'visitor', type: '', q: '' };
export default function TravelAnalyticsPanel({ refreshKey = 0 }) {
  const [filters, setFilters] = useState(initial), [page, setPage] = useState(1), [refresh, setRefresh] = useState(0), [visitor, setVisitor] = useState('');
  const [data, setData] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [paused, setPaused] = useState(false);
  useEffect(() => {
    const controller = new AbortController(); setLoading(true); setError('');
    adminRequest(`/analytics/v2?${new URLSearchParams({ ...filters, page: String(page), limit: '25' })}`, { signal: controller.signal }).then(setData).catch(e => { if (e.name !== 'AbortError') setError(e.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [filters, page, refresh, refreshKey]);
  useEffect(() => { if (paused) return; const timer = setInterval(() => { if (document.visibilityState === 'visible') setRefresh(r => r + 1); }, 30000); return () => clearInterval(timer); }, [paused]);
  function change(key, value) { setFilters(f => ({ ...f, [key]: value })); setPage(1); setVisitor(''); setData(null); }
  const totals = data?.totals || {}, funnel = data?.funnel || {};
  const stages = ['hotel_view', 'room_select', 'checkout_view', 'payment_start', 'payment_ready', 'booking_confirmed'];
  return <section className="analyticsV2" aria-label="Analytics V2"><header className="avHeading"><div><span className="adminEyebrow">ROTAVOY INSIGHTS</span><h2>Analytics <span>V2</span></h2><p>Ziyaretten rezervasyon yolculuğuna.</p></div><div className="avActions"><button onClick={() => setPaused(p => !p)}>{paused ? 'Canlı yenilemeyi aç' : 'Canlı yenilemeyi durdur'}</button><button disabled={loading} onClick={() => setRefresh(r => r + 1)}>Yenile</button></div></header>
    <div className="avFilters"><label>Dönem<select value={filters.days} onChange={e => { setFilters(f => ({ ...f, days: e.target.value, from: '', to: '' })); setPage(1); setVisitor(''); setData(null); }}>{[['1', 'Son 24 saat'], ['7', 'Son 7 gün'], ['30', 'Son 30 gün'], ['90', 'Son 90 gün']].map(([v, t]) => <option value={v} key={v}>{t}</option>)}</select></label><label>Başlangıç (UTC)<input type="date" value={filters.from} onChange={e => change('from', e.target.value)} /></label><label>Bitiş (UTC)<input type="date" value={filters.to} onChange={e => change('to', e.target.value)} /></label><label>Ziyaretçi türü<select value={filters.traffic} onChange={e => change('traffic', e.target.value)}>{Object.entries(trafficLabels).map(([v, t]) => <option key={v} value={v}>{t}</option>)}</select></label><label>Ülke<input list="av-countries" placeholder="Örn. Germany" value={filters.country} onChange={e => change('country', e.target.value)} /></label><label>Trafik kaynağı<input list="av-sources" placeholder="Örn. reddit / direct" value={filters.source} onChange={e => change('source', e.target.value)} /></label><label>Hareket türü<select value={filters.type} onChange={e => change('type', e.target.value)}><option value="">Tüm hareketler</option>{Object.entries(eventLabels).filter(([key]) => key !== 'heartbeat').map(([key, title]) => <option key={key} value={key}>{title}</option>)}</select></label><label>Otel, rota veya ziyaretçi<input maxLength="100" value={filters.q} onChange={e => change('q', e.target.value)} /></label><button onClick={() => { setFilters(initial); setPage(1); setVisitor(''); setData(null); }}>Sıfırla</button></div>
    <datalist id="av-countries">{data?.countries?.filter(i => i._id).map(i => <option key={i._id} value={i._id} />)}</datalist><datalist id="av-sources">{data?.sources?.filter(i => i._id).map(i => <option key={i._id} value={i._id} />)}</datalist><p className="avNotice">{trafficLabels[filters.traffic]} görünümü. Standart trafik, yönetici/test ve şüpheli botları dışlar; insan olduğunun kesin kanıtı değildir. Eski işaretsiz kayıtlar belirsizdir. IP veya ülke sınıflandırma kanıtı sayılmaz.</p>
    {error && <p className="adminError" role="alert">{error} <button onClick={() => setRefresh(r => r + 1)}>Tekrar dene</button></p>}{loading && <p className="adminHint" role="status">Veriler güncelleniyor…</p>}
    {data && <><div className="avMetrics">{[['Tekil ziyaretçi', totals.visitors], ['Oturum', totals.sessions], ['Sayfa görüntüleme', totals.pageViews], ['Doğrulanmış rezervasyon', data.confirmed?.[0]?.count || 0], ['Şu an aktif', data.live]].map(([label, count]) => <article key={label}><span>{label}</span><strong>{count || 0}</strong>{label === 'Şu an aktif' && <small>Son 90 saniye · seçili filtreler</small>}</article>)}</div>
    <div className="avGridMain"><Trend items={data.trend} from={data.from} to={data.to} /><section className="avPanel"><h3>Rezervasyon yolculuğu<small>Sıralı adımlar · tekil oturum</small></h3><div className="avFunnel">{stages.map((stage, i) => <div key={stage}><span>{i + 1}. {eventLabels[stage]}</span><b>{funnel[stage] || 0}</b><div><i style={{ width: `${(funnel[stage] || 0) / Math.max(1, funnel.hotel_view || 0) * 100}%` }} /></div></div>)}</div><p className="adminHint">Son adım sunucudaki onaylı rezervasyon kaydıyla doğrulanır. Aynı oturumda önceki adımları sırasıyla tamamlayanlar sayılır. Tarayıcıya geri dönülmeyen rezervasyonlar ölçülemeyebilir.</p></section></div>
    <div className="avThree"><Breakdown title="Trafik kaynakları" items={data.sources} /><Breakdown title="Ülkeler" items={data.countries} /><Breakdown title="Cihazlar" items={data.devices} /></div>
    <div className="avThree"><Breakdown title="İncelenen oteller" items={data.hotels} label={i => i.name || i._id || 'Bilinmiyor'} unit="görüntüleme" /><Breakdown title="Uçuş aramaları" items={data.flights} label={i => `${i._id.origin || '?'} → ${i._id.destination || '?'}`} unit="arama" /><Breakdown title="Hareket dağılımı" items={data.types?.slice(0, 8)} label={i => eventLabels[i._id] || i._id} unit="olay" /></div>
    <section className="avPanel"><div className="avBetween"><h3>Ziyaretçiler <small>{totals.visitors} kayıt</small></h3><button disabled={!data.visitors?.length} onClick={() => downloadAdminCsv(data.visitors.map(i => ({ ziyaretci: i._id, ulke: i.country, kaynak: i.source, cihaz: i.device, hareket: i.events, trafik: i.trafficTypes?.join(', '), son_gorulme: i.lastSeen })), 'rotavoy-analytics-v2.csv')}>Bu sayfayı CSV indir</button></div><div className="avVisitors">{data.visitors?.map(item => <article key={item._id}><button className="avVisitor" aria-expanded={visitor === item._id} aria-controls={`journey-${item._id}`} onClick={() => setVisitor(v => v === item._id ? '' : item._id)}><span className="avAvatar">{item.device === 'Mobil' ? 'M' : 'V'}</span><span><strong>Ziyaretçi {item._id.slice(-8)}</strong><small>{item.country || 'Ülke bilinmiyor'} · {item.device || '—'} · {item.browser || '—'}</small></span><span><strong>{item.source || 'direct'}</strong><small>{item.trafficTypes?.map(t => trafficLabels[t]).join(' · ')}</small></span><span><strong>{item.events} hareket · {item.sessionCount || 1} oturum</strong><small>{date(item.lastSeen)}</small></span><span aria-hidden="true">{visitor === item._id ? '−' : '+'}</span></button>{visitor === item._id && <div id={`journey-${item._id}`}><Journey visitorId={item._id} filters={filters} refresh={refresh + refreshKey} /></div>}</article>)}</div>{!data.visitors?.length && <p className="adminEmpty">Bu filtrelerde ziyaretçi yok. Tarih aralığını veya ziyaretçi türünü değiştirebilirsin.</p>}<div className="adminPagination"><span>Sayfa {page} / {Math.max(1, Math.ceil(totals.visitors / 25))}</span><button disabled={loading || page === 1} onClick={() => { setPage(p => p - 1); setVisitor(''); }}>Önceki</button><button disabled={loading || page * 25 >= totals.visitors} onClick={() => { setPage(p => p + 1); setVisitor(''); }}>Sonraki</button></div></section>
    <footer className="adminHint">Son güncelleme: {date(data.generatedAt)} · {paused ? 'Otomatik yenileme duraklatıldı' : '30 saniyede yenilenir'} · Konum yaklaşık; hareket saatleri tarayıcının saat dilimindedir.</footer></>}
  </section>;
}
