import { useEffect, useRef, useState } from 'react';
import { Link, NavLink, useLocation, useNavigate } from 'react-router-dom';
import { LayoutDashboard, CalendarCheck, CreditCard, Users, Hotel, Headphones, FileText, Settings, Activity, Plug, Plane, CarFront, MapPinned, RefreshCw, Download, Plus, ArrowUpRight, Moon, Sun } from 'lucide-react';
import { getAdminSession, loginAdmin, logoutAdmin } from '../services/adminSession';
import RotavoyLogo from '../components/Brand/RotavoyLogo';
import Seo from '../components/Seo/Seo';
import AdminRecordEditor, { statusLabels } from '../components/Admin/AdminRecordEditor';
import { adminRequest, downloadAdminCsv } from '../services/adminApi';
import TravelAnalyticsPanel from '../components/Admin/TravelAnalyticsPanel';
import './TravelAdmin.css';
const sections = [ ['overview', 'Genel bakış', LayoutDashboard], ['analytics', 'Ziyaretçi analitiği', Activity], ['bookings', 'Rezervasyonlar', CalendarCheck], ['payments', 'Ödemeler', CreditCard], ['customers', 'Müşteriler', Users], ['hotels', 'Otel vitrini', Hotel], ['tickets', 'Destek / iptal / iade', Headphones], ['content', 'Destinasyon ve içerik', FileText], ['providers', 'Sağlayıcılar ve servisler', Plug], ['settings', 'Operasyon ayarları', Settings], ['audit', 'İşlem geçmişi', Activity], ['roadmap', 'Geliştirme alanları', Plane] ];
const paginated = ['bookings', 'payments', 'customers', 'hotels', 'tickets', 'content', 'audit'];
const date = value => value ? new Date(value).toLocaleString('tr-TR') : '—';
const money = (value, currency) => new Intl.NumberFormat('tr-TR', { style: 'currency', currency: /^[A-Z]{3}$/.test(currency || '') ? currency : 'USD' }).format(value || 0);
const label = value => statusLabels[value] || value || '—';
function Badge({ value }) { return <span className={`adminBadge adminBadge--${value}`}>{label(value)}</span>; }
function Empty() { return <p className="adminEmpty">Bu filtreye uygun kayıt yok. Gerçek kayıtlar oluştukça burada görünecek.</p>; }
function SettingsForm({ settings, onSaved }) {
  const [form, setForm] = useState(settings); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function save(event) { event.preventDefault(); setBusy(true); setError(''); try { await adminRequest('/settings', { method: 'PUT', body: { ...form, marginPercent: Number(form.marginPercent) } }); onSaved(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <form className="adminEditor" onSubmit={save}><h2>Operasyon iletişim bilgileri</h2><p className="adminHint">Bu bilgiler yönetim panelinde saklanır. Komisyon oranı yeni otel aramalarına uygulanır; mevcut teklifler ve rezervasyon tutarları değiştirilmez. Ödeme anahtarları sunucu yapılandırmasındadır.</p><fieldset disabled={busy}><div className="adminFormGrid">{[['marginPercent', 'Otel komisyon oranı (%)'], ['supportEmail', 'Destek e-postası'], ['supportPhone', 'Destek telefonu'], ['announcement', 'Ekip operasyon notu']].map(([key, title]) => <label key={key}>{title}<input type={key === 'marginPercent' ? 'number' : key === 'supportEmail' ? 'email' : 'text'} min={key === 'marginPercent' ? 0 : undefined} max={key === 'marginPercent' ? 100 : undefined} step={key === 'marginPercent' ? '0.1' : undefined} required={key === 'marginPercent'} maxLength={key === 'announcement' ? 500 : 254} value={form[key] ?? ''} onChange={event => setForm({ ...form, [key]: event.target.value })} /></label>)}</div><button className="adminPrimary">{busy ? 'Kaydediliyor…' : 'Ayarları kaydet'}</button></fieldset>{error && <p className="adminError" role="alert">{error}</p>}</form>;
}
function BookingDetails({ reference, onClose, onTicket }) {
  const [data, setData] = useState(null); const [note, setNote] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => { const controller = new AbortController(); adminRequest(`/bookings/${encodeURIComponent(reference)}`, { signal: controller.signal }).then(result => { setData(result); setNote(result.note); }).catch(err => { if (err.name !== 'AbortError') setError(err.message); }); return () => controller.abort(); }, [reference]);
  async function save(event) { event.preventDefault(); setBusy(true); setError(''); setSaved(false); try { await adminRequest(`/bookings/${encodeURIComponent(reference)}/note`, { method: 'PUT', body: { note } }); setSaved(true); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <section className="adminEditor"><div className="adminSectionHeading"><h2>{reference}</h2><button onClick={onClose}>Kapat</button></div>{error && <p role="alert" className="adminError">{error}</p>}{!data && !error && <p>Rezervasyon yükleniyor…</p>}{data && <><div className="adminDetailsGrid"><div><h3>Müşteri</h3><p>{data.booking.holder?.firstName} {data.booking.holder?.lastName}</p><p>{data.booking.holder?.email}</p><p>{data.booking.holder?.phone || 'Telefon yok'}</p></div><div><h3>Rezervasyon / ödeme</h3><p><Badge value={data.booking.status} /> <Badge value={data.booking.paymentStatus} /></p><p>{money(data.booking.total, data.booking.currency)}</p><p>{data.booking.payment?.method || 'Ödeme yöntemi yok'} · {data.booking.payment?.token || ''} {data.booking.payment?.networkKey || ''}</p><p>Oluşturma: {date(data.booking.createdAt)}</p><p>Sağlayıcı ref.: {data.booking.providerReference || 'Henüz yok'}</p></div></div>{data.booking.payment?.transactionHash && <p className="adminMono">TX: {data.booking.payment.transactionHash}</p>}{data.booking.failureReason && <p className="adminError">{data.booking.failureReason}</p>}{data.booking.kind === 'flight' && <><h3>Uçuş güzergâhı</h3>{data.booking.flight?.segments?.map((s, i) => <p key={i}>{s.originCode} → {s.destinationCode} · {s.departureTime?.replace('T', ' ')} · {s.arrivalTime?.replace('T', ' ')}</p>)}<p>Uçuş referansı: {data.booking.reservation?.bookingRef || 'Bekleniyor'}</p></>}<h3>{data.booking.kind === 'flight' ? 'Seyahat kaydı' : 'Checkout konaklama seçimi'}</h3><p>{data.booking.stay?.hotelName || "Otel bilgisi bu kayıtta saklanmamış"} · {data.booking.stay?.checkin || "—"} → {data.booking.stay?.checkout || "—"} · {data.booking.stay?.adults || "—"} kişi</p><p className="adminHint">Checkout seçimi bilgi amaçlıdır; sağlayıcının onayladığı rezervasyon koşulları esas alınır. Eski kayıtlarda bu alanlar bulunmayabilir.</p><h3>Misafirler</h3><ul>{(data.booking.guests || []).map((guest, index) => <li key={index}>{guest.firstName} {guest.lastName}</li>)}</ul><form onSubmit={save}><label>Operasyon notu<textarea rows="4" maxLength="3000" value={note} onChange={event => { setNote(event.target.value); setSaved(false); }} /></label><div className="adminToolbar"><button disabled={busy} className="adminPrimary">{busy ? 'Kaydediliyor…' : 'Notu kaydet'}</button><button type="button" onClick={() => onTicket({ subject: `${reference} — destek`, email: data.booking.holder?.email || '', clientReference: reference, type: 'support', status: 'open', priority: 'normal', note: '' })}>Destek kaydı aç</button></div>{saved && <p role="status">Not kaydedildi.</p>}</form></>}</section>;
}
function HotelShowcaseEditor({ hotel, onClose, onSaved }) {
  const [visible, setVisible] = useState(hotel.showcaseVisible !== false);
  const [priority, setPriority] = useState(hotel.showcasePriority || 0);
  const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function save(event) { event.preventDefault(); setBusy(true); setError(''); try { await adminRequest(`/hotels/${encodeURIComponent(hotel.hotelId)}/showcase`, { method: 'PUT', body: { showcaseVisible: visible, showcasePriority: Number(priority) } }); onSaved(); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <form className="adminEditor" onSubmit={save}><div className="adminSectionHeading"><h2>{hotel.name} — vitrin</h2><button type="button" onClick={onClose}>Kapat</button></div><p className="adminHint">Görünürlük anasayfa vitrini içindir. Gizli oteller müşteri aramasında bulunabilir. Öncelik indeks sıralamasını etkiler; müsaitlik ve destinasyon çeşitliliği de vitrinde etkilidir.</p><fieldset disabled={busy}><div className="adminFormGrid"><label>Vitrin görünürlüğü<select value={visible ? 'visible' : 'hidden'} onChange={event => setVisible(event.target.value === 'visible')}><option value="visible">Göster</option><option value="hidden">Gizle</option></select></label><label>Öncelik (0–100)<input required type="number" min="0" max="100" step="1" value={priority} onChange={event => setPriority(event.target.value)} /></label></div><button className="adminPrimary">{busy ? 'Kaydediliyor…' : 'Vitrini kaydet'}</button></fieldset>{error && <p className="adminError" role="alert">{error}</p>}</form>;
}
function Providers({ data }) {
  const checks = [['Nuitee / LiteAPI', data.nuitee?.configured, data.nuitee?.environment], ['Veritabanı', data.database, 'MongoDB'], ['Firebase', data.firebaseConfigured, 'Müşteri girişi'], ['Kart anahtarı override', data.cardPublishableKeyConfigured, 'Boşsa sağlayıcı SDK yanıtından alınabilir'], ['Kripto alıcı cüzdanı', data.cryptoWalletConfigured, 'Sunucu yapılandırması'], ['Canlı otel rezervasyonu izni', data.liveBookingEnabled, 'Sunucu yapılandırması']];
  return <><div className="adminIntegrationGrid">{checks.map(([title, configured, detail]) => <article className="adminPanel" key={title}><h3>{title}</h3><span className={`adminBadge ${configured ? 'adminBadge--confirmed' : ''}`}>{configured ? 'Yapılandırılmış' : 'Yapılandırılmamış'}</span><p>{detail}</p></article>)}</div><p className="adminHint">Bu göstergeler yapılandırma durumudur; sağlayıcının anlık erişilebilirlik testi değildir. Sandbox rezervasyonu: {data.nuitee?.sandboxBookingEnabled ? 'Açık' : 'Kapalı'}. Etkin komisyon ayarı: %{data.marginPercent}. Anahtarlar panelde gösterilmez.</p><div className="adminTableWrap"><table><thead><tr><th>Kategori</th><th>Arama</th><th>Rezervasyon</th><th>Sayfa</th></tr></thead><tbody>{data.services.map(service => <tr key={service.key}><td>{{ hotels: 'Oteller', flights: 'Uçuşlar', cars: 'Araç kiralama', activities: 'Aktiviteler' }[service.key]}</td><td>{service.search && data.nuitee?.configured ? 'Bağlı' : 'Bağlantı bekliyor'}</td><td>{service.booking ? (service.key === 'flights' ? 'Yolcu, ödeme ve biletleme akışı mevcut; Nuitee production yetkisi gerekir' : 'Otel ödeme ve rezervasyon akışı mevcut; sağlayıcı hesabına bağlı') : 'Entegrasyon bekliyor'}</td><td><Link to={`/${service.key}`} target="_blank" rel="noreferrer">Aç <ArrowUpRight size={14} /></Link></td></tr>)}</tbody></table></div></>;
}
function Roadmap() {
  return <div className="adminIntegrationGrid">{[[Plane, 'Uçuş operasyonu', 'Arama ve teklif doğrulama mevcut. Biletleme, PNR, e-bilet, değişiklik ve sağlayıcı iptali için entegrasyon gerekiyor.'], [CarFront, 'Araç kiralama', 'Planlama sayfası mevcut. Sağlayıcı teklifleri, araç sınıfı, depozito, teslim alma ve rezervasyon bağlantısı bekliyor.'], [MapPinned, 'Aktiviteler', 'Planlama sayfası mevcut. Müsaitlik, saat dilimleri, bilet/voucher ve iptal koşulları için sağlayıcı gerekiyor.'], [CreditCard, 'Finans ve mutabakat', 'Gerçek rezervasyon ödemeleri listeleniyor. Sağlayıcı payout, iade transferi, net komisyon ve banka mutabakatı entegrasyon bekliyor.'], [Users, 'Ekip ve roller', 'Yönetici erişimi şifreli oturumla sağlanır. Operatör, finans ve içerik rolleri ileride ayrı yetkilerle eklenebilir.'], [FileText, 'İçerik yayını', 'Destinasyon, kampanya ve rehber taslakları saklanabilir. Yayın akışı, SEO sayfaları ve zamanlama sonraki entegrasyon alanı.']].map(([Icon, title, description]) => <article className="adminPanel" key={title}><Icon size={26} /><h3>{title}</h3><span className="adminBadge">Entegrasyon bekliyor</span><p>{description}</p></article>)}</div>;
}
function AdminThemeToggle({ dark, onToggle }) {
  return <button type="button" className="adminThemeToggle" aria-pressed={dark} aria-label="Koyu tema" title={dark ? 'Açık temaya geç' : 'Koyu temaya geç'} onClick={onToggle}>{dark ? <Sun size={18} /> : <Moon size={18} />}<span>{dark ? 'Açık tema' : 'Koyu tema'}</span></button>;
}
export default function TravelAdmin() {
  const [dark, setDark] = useState(() => { try { return localStorage.getItem('rotavoy_admin_theme') === 'dark'; } catch { return false; } });
  useEffect(() => { try { localStorage.setItem('rotavoy_admin_theme', dark ? 'dark' : 'light'); } catch { /* Theme still works when browser storage is unavailable. */ } }, [dark]);
  const themeToggle = <AdminThemeToggle dark={dark} onToggle={() => setDark(value => !value)} />;
  const [customerSession, setAdminSession] = useState(getAdminSession);
  const [loginBusy, setLoginBusy] = useState(false);
  const [password, setPassword] = useState('');
  const isAuthenticated = Boolean(customerSession?.token);
  async function submitLogin(event) {
    event.preventDefault();
    if (loginBusy) return;
    setLoginBusy(true); setAccessError('');
    try { setAdminSession(await loginAdmin(password)); setPassword(''); }
    catch (err) { setAccessError(err.message || 'Yönetici girişi tamamlanamadı.'); }
    finally { setLoginBusy(false); }
  }
  async function signOut() { try { await logoutAdmin(); setAdminSession(null); } catch (err) { setAccessError(err.message); setError(err.message); } }
  const location = useLocation(); const navigate = useNavigate();
  const section = location.pathname.split('/')[2] || 'overview';
  const current = sections.find(item => item[0] === section);
  const [access, setAccess] = useState('loading'); const [admin, setAdmin] = useState(null); const [accessError, setAccessError] = useState('');
  const [loadedData, setLoadedData] = useState(null);
  const data = loadedData?.section === section ? loadedData.payload : null;
  const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const [query, setQuery] = useState(''); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [page, setPage] = useState(1); const [refresh, setRefresh] = useState(0);
  const [hotelEdit, setHotelEdit] = useState(null);
  const [editor, setEditor] = useState(null); const [reference, setReference] = useState(''); const [success, setSuccess] = useState('');
  const contentRef = useRef(null);
  useEffect(() => { if (!isAuthenticated) { setAccess('login'); return undefined; } const controller = new AbortController(); setAccess('loading'); setAccessError(''); adminRequest('/session', { signal: controller.signal }).then(result => { setAdmin(result.admin); setAccess('allowed'); }).catch(err => { if (err.name !== 'AbortError') { setAccess('denied'); setAccessError(err.message); } }); return () => controller.abort(); }, [isAuthenticated, customerSession?.token]);
  useEffect(() => { setHotelEdit(null); setQuery(''); setSearch(''); setStatus(''); setPage(1); setEditor(section === 'tickets' && location.state?.ticketDraft ? { kind: 'tickets', record: location.state.ticketDraft } : null); setReference(''); setSuccess(''); }, [section, location.state]);
  useEffect(() => {
    if (access !== 'allowed' || !current || ['roadmap', 'analytics'].includes(section)) return undefined;
    const controller = new AbortController(); setLoading(true); setError(''); setLoadedData(null);
    const endpoint = section === 'payments' ? 'bookings' : section;
    const params = new URLSearchParams({ page: String(page), limit: '25', ...(search ? { q: search } : {}), ...(status ? { [section === 'payments' ? 'paymentStatus' : 'status']: status } : {}) });
    adminRequest(`/${endpoint}${paginated.includes(section) ? `?${params}` : ''}`, { signal: controller.signal }).then(result => setLoadedData({ section, payload: result })).catch(err => { if (err.name !== 'AbortError') { setError(err.message); if ([401, 403].includes(err.status)) { setAccess('denied'); setAccessError(err.message); } } }).finally(() => { if (!controller.signal.aborted) setLoading(false); });
    return () => controller.abort();
  }, [access, section, page, search, status, refresh, current]);
  function reload(message = '') { setRefresh(value => value + 1); setEditor(null); setSuccess(message); }
  function exportRows() {
    const items = data?.items || []; const rows = items.map(item => section === 'bookings' || section === 'payments' ? { referans: item.clientReference, musteri: `${item.holder?.firstName || ''} ${item.holder?.lastName || ''}`, email: item.holder?.email, rezervasyon: label(item.status), odeme: label(item.paymentStatus), otel: item.stay?.hotelName, giris: item.stay?.checkin, cikis: item.stay?.checkout, tutar: item.total, para_birimi: item.currency, tarih: item.createdAt } : Object.fromEntries(Object.entries(item).filter(([, value]) => typeof value !== 'object')));
    downloadAdminCsv(rows, `rotavoy-${section}-sayfa-${page}.csv`);
  }
  const seo = <Seo title="Travel Yönetimi | Rotavoy" description="Rotavoy Travel operasyon yönetimi." path={location.pathname} noIndex />;
  if (access !== 'allowed') return <div className="adminGateSurface" data-theme={dark ? "dark" : "light"}><main className="adminGate">{themeToggle}{seo}<Link to="/"><RotavoyLogo className="adminLogo" /></Link><h1>Rotavoy Travel Yönetimi</h1>{access === 'loading' ? <p role="status">Yönetici erişimi kontrol ediliyor…</p> : <><p>Yönetici şifrenle giriş yap.</p>{accessError && <p className="adminLoginError" role="alert">{accessError}</p>}<form className="adminLoginForm" onSubmit={submitLogin}><label htmlFor="admin-password">Şifre</label><input id="admin-password" name="password" type="password" autoComplete="current-password" value={password} onChange={event => setPassword(event.target.value)} required maxLength={1024} disabled={loginBusy} /><button type="submit" className="adminPrimary" disabled={loginBusy || !password}>{loginBusy ? 'Giriş yapılıyor…' : 'Giriş yap'}</button></form>{isAuthenticated && <button onClick={signOut}>Çıkış yap</button>}<Link to="/">Siteye dön</Link></>}</main></div>;
  return <div className="travelAdmin" data-theme={dark ? "dark" : "light"}>{seo}<aside className="adminSidebar"><Link to="/"><RotavoyLogo className="adminLogo" /></Link><span className="adminEyebrow">TRAVEL OPERASYON</span><nav aria-label="Travel yönetimi">{sections.map(([key, title, Icon]) => <NavLink key={key} to={key === 'overview' ? '/admin' : `/admin/${key}`} end><Icon size={19} />{title}</NavLink>)}</nav><div className="adminSidebarBottom"><p>{admin?.identity}</p><Link to="/">Siteye dön <ArrowUpRight size={16} /></Link><button onClick={signOut}>Çıkış yap</button></div></aside><main className="adminMain" ref={contentRef}><header className="adminTopbar"><div><span className="adminEyebrow">ROTAVOY TRAVEL</span><h1>{current?.[1] || 'Sayfa bulunamadı'}</h1></div><div className="adminTopbarActions">{themeToggle}<button disabled={loading} onClick={() => reload()} aria-label="Verileri yenile"><RefreshCw size={18} />Yenile</button></div></header>
    {!current && <p><Link to="/admin">Genel bakışa dön</Link></p>}
    {success && <p className="adminSuccess" role="status">{success}</p>}{error && <p className="adminError" role="alert">{error}</p>}
    {paginated.includes(section) && <div className="adminToolbar"><form onSubmit={event => { event.preventDefault(); setSearch(query); setPage(1); }}><label className="adminSearchLabel">Kayıtlarda ara<input aria-label="Kayıtlarda ara" value={query} onChange={event => setQuery(event.target.value)} maxLength="100" placeholder={section === 'bookings' || section === 'payments' ? 'Referans, isim veya e-posta' : 'Kayıtlarda ara'} /></label><button type="submit">Ara</button></form>{['bookings', 'payments', 'tickets', 'content'].includes(section) && <label>Durum<select value={status} onChange={event => { setStatus(event.target.value); setPage(1); }}><option value="">Tümü</option>{(section === 'bookings' ? ['awaiting_payment', 'processing', 'confirmed', 'failed', 'expired'] : section === 'payments' ? ['unpaid', 'pending', 'paid', 'failed'] : section === 'tickets' ? ['open', 'in_progress', 'waiting_provider', 'resolved'] : ['draft', 'ready', 'archived']).map(value => <option key={value} value={value}>{label(value)}</option>)}</select></label>}<button disabled={!data?.items?.length} onClick={exportRows}><Download size={16} />Bu sayfayı CSV indir</button>{['tickets', 'content'].includes(section) && <button className="adminPrimary" onClick={() => setEditor({ kind: section, record: null })}><Plus size={16} />Yeni kayıt</button>}</div>}
    {loading && <p className="adminEmpty" role="status">Veriler yükleniyor…</p>}
    {hotelEdit && <HotelShowcaseEditor key={hotelEdit.hotelId} hotel={hotelEdit} onClose={() => setHotelEdit(null)} onSaved={() => { setHotelEdit(null); reload("Vitrin ayarı kaydedildi. Yenilenen anasayfa bu ayarı kullanır."); }} />}
    {editor && <AdminRecordEditor key={`${editor.kind}-${editor.record?._id || 'new'}`} {...editor} onClose={() => setEditor(null)} onSaved={() => reload('Kayıt kaydedildi.')} />}
    {reference && <BookingDetails key={reference} reference={reference} onClose={() => setReference('')} onTicket={record => { navigate('/admin/tickets', { state: { ticketDraft: record } }); }} />}
    {data && section === 'overview' && <><div className="adminMetricGrid">{[['Rezervasyon', data.bookingStatus.reduce((sum, item) => sum + item.count, 0), CalendarCheck], ['Müşteri', data.customers, Users], ['Açık destek kaydı', data.tickets, Headphones], ['Otel indeksinde', data.hotels, Hotel]].map(([title, value, Icon]) => <article className="adminMetric" key={title}><Icon size={23} /><span>{title}</span><strong>{value}</strong></article>)}</div><div className="adminDetailsGrid"><section className="adminPanel"><h2>Rezervasyon durumları</h2>{data.bookingStatus.length ? data.bookingStatus.map(item => <p className="adminSummaryLine" key={`${item._id.status}-${item._id.paymentStatus}`}><span>{label(item._id.status)} / {label(item._id.paymentStatus)}</span><strong>{item.count}</strong></p>) : <Empty />}</section><section className="adminPanel"><h2>Ödenen brüt rezervasyon tutarı</h2><p className="adminHint">Para birimleri ayrı gösterilir. Bu tutar net komisyon veya banka hesabına aktarılan bakiye değildir.</p>{data.totals.length ? data.totals.map(item => <p className="adminSummaryLine" key={item._id}><span>{item.count} rezervasyon</span><strong>{money(item.gross, item._id)}</strong></p>) : <Empty />}</section></div><div className="adminQuickLinks"><Link to="/admin/bookings">Rezervasyonları incele</Link><Link to="/admin/tickets">Destek operasyonu</Link><Link to="/admin/providers">Servis durumları</Link></div></>}
    {data && ['bookings', 'payments'].includes(section) && <><p className="adminHint">Mevcut kayıtlar otel rezervasyonlarına aittir. Uçuş, araç ve aktivite rezervasyonları sağlayıcıları bağlandıktan sonra eklenebilir.</p><div className="adminTableWrap"><table><thead><tr><th>Referans / tarih</th><th>Müşteri / otel</th><th>Rezervasyon</th><th>Ödeme</th><th>Tutar</th><th>İşlem</th></tr></thead><tbody>{data.items.map(item => <tr key={item.clientReference}><td><strong>{item.clientReference}</strong><small>{date(item.createdAt)}</small></td><td>{item.holder?.firstName} {item.holder?.lastName}<small>{item.holder?.email}</small><small>{item.stay?.hotelName || "Konaklama bilgisi kaydedilmemiş"}</small></td><td><Badge value={item.status} /></td><td><Badge value={item.paymentStatus} /><small>{item.payment?.method || '—'}</small></td><td>{money(item.total, item.currency)}</td><td><button onClick={() => setReference(item.clientReference)}>Detay</button></td></tr>)}</tbody></table></div></>}
    {data && section === 'customers' && <div className="adminTableWrap"><table><thead><tr><th>Müşteri</th><th>E-posta</th><th>Giriş türü</th><th>Son giriş</th><th>Kayıt</th></tr></thead><tbody>{data.items.map(item => <tr key={item._id}><td>{item.profile?.fullName || item.displayName || 'Misafir'}</td><td>{item.email || item.profile?.email || '—'}<small>{item.emailVerified ? 'Doğrulanmış' : 'Doğrulanmamış'}</small></td><td>{item.provider}</td><td>{date(item.lastLoginAt)}</td><td>{date(item.createdAt)}</td></tr>)}</tbody></table></div>}
    {data && section === 'hotels' && <><p className="adminHint">Bu liste Nuitee kataloğunun tamamı değil, yerel vitrin indeksidir. Fiyat ve müsaitlik aramada sağlayıcıdan alınır.</p><div className="adminTableWrap"><table><thead><tr><th>Otel</th><th>Konum</th><th>Yıldız</th><th>Video / vitrin</th><th>Son kontrol</th><th>İşlem</th></tr></thead><tbody>{data.items.map(item => <tr key={item.hotelId}><td>{item.name}<small>{item.hotelId}</small></td><td>{item.cityName} / {item.countryCode}</td><td>{item.stars}</td><td>{item.hasVideo ? 'Var' : 'Yok'}<small>{item.showcaseVisible === false ? 'Vitrinden gizli' : 'Vitrinde'} · Öncelik {item.showcasePriority || 0}</small></td><td>{date(item.checkedAt)}</td><td><button onClick={() => setHotelEdit(item)}>Vitrini düzenle</button><br /><Link to={`/travel/hotels/${encodeURIComponent(item.hotelId)}`} target="_blank" rel="noreferrer">Oteli aç</Link></td></tr>)}</tbody></table></div></>}
    {data && ['tickets', 'content'].includes(section) && <div className="adminTableWrap"><table><thead><tr><th>{section === 'tickets' ? 'Konu / referans' : 'Başlık / destinasyon'}</th><th>Tür</th><th>Durum</th><th>Güncelleme</th><th>İşlem</th></tr></thead><tbody>{data.items.map(item => <tr key={item._id}><td>{item.subject || item.title}<small>{item.clientReference || item.destination || item.email}</small></td><td>{label(item.type)}{item.priority && <small>{label(item.priority)}</small>}</td><td><Badge value={item.status} /></td><td>{date(item.updatedAt)}</td><td><button onClick={() => setEditor({ kind: section, record: item })}>Düzenle</button></td></tr>)}</tbody></table></div>}
    {data && section === 'providers' && <Providers data={data} />}
    {data && section === 'settings' && <SettingsForm key={refresh} settings={data.settings} onSaved={() => reload('Ayarlar kaydedildi.')} />}
    {data && section === 'audit' && <div className="adminTableWrap"><table><thead><tr><th>Tarih</th><th>Yönetici</th><th>İşlem</th><th>Hedef</th></tr></thead><tbody>{data.items.map(item => <tr key={item._id}><td>{date(item.createdAt)}</td><td>{item.actor}</td><td>{item.action}</td><td>{item.target}</td></tr>)}</tbody></table></div>}
    {section === 'analytics' && <TravelAnalyticsPanel refreshKey={refresh} />}
    {section === 'roadmap' && <Roadmap />}
    {data?.items?.length === 0 && <Empty />}
    {data && paginated.includes(section) && <div className="adminPagination"><span>{data.total} kayıt · Sayfa {page} / {Math.max(1, Math.ceil(data.total / data.limit))}</span><button disabled={page <= 1 || loading} onClick={() => setPage(value => value - 1)}>Önceki</button><button disabled={page * data.limit >= data.total || loading} onClick={() => setPage(value => value + 1)}>Sonraki</button></div>}
  </main></div>;
}

