import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createApp } from '../src/app.js';
import { AdminSession } from '../src/models/AdminSession.js';
import { CustomerSession } from '../src/models/CustomerSession.js';
import { createCustomerSession } from '../src/services/customerAuthService.js';

test('password admin login, expiry, rotation, logout and customer isolation', async () => {
  const previous = process.env.ROTAVOY_ADMIN_PASSWORD;
  const originalAdmin = { create: AdminSession.create, find: AdminSession.findOne, remove: AdminSession.deleteOne };
  const originalCustomer = { create: CustomerSession.create, find: CustomerSession.findOne, remove: CustomerSession.deleteOne };
  const admins = new Map(); const customers = new Map();
  const customer = { _id: 'customer-fixture', provider: 'firebase', providerId: 'google-fixture', email: 'owner@example.com', emailVerified: true };
  AdminSession.create = async body => { const stored = { ...body, _id: body.tokenHash }; admins.set(body.tokenHash, stored); return stored; };
  AdminSession.findOne = async filter => { const session = admins.get(filter.tokenHash); return session && session.credentialVersion === filter.credentialVersion && session.expiresAt > filter.expiresAt.$gt ? session : null; };
  AdminSession.deleteOne = async filter => { admins.delete(filter._id); };
  CustomerSession.create = async body => { const stored = { ...body, _id: body.tokenHash, customer, lastUsedAt: new Date() }; customers.set(body.tokenHash, stored); return stored; };
  CustomerSession.findOne = filter => ({ populate: async () => customers.get(filter.tokenHash) || null });
  CustomerSession.deleteOne = async filter => { customers.delete(filter._id); };
  const server = createApp().listen(0); await once(server, 'listening');
  const base = `http://127.0.0.1:${server.address().port}`;
  const login = password => fetch(`${base}/api/admin-auth/password`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ password }) });
  const request = (path, token, method = 'GET') => fetch(`${base}${path}`, { method, headers: { Authorization: `Bearer ${token}` } });
  try {
    delete process.env.ROTAVOY_ADMIN_PASSWORD;
    assert.equal((await login('anything')).status, 503);
    process.env.ROTAVOY_ADMIN_PASSWORD = 'test-admin-password';
    assert.equal((await login('wrong-password')).status, 401);
    assert.equal((await login({ password: 'test-admin-password' })).status, 401);
    const result = await login('test-admin-password');
    assert.equal(result.status, 201); assert.equal(result.headers.get('cache-control'), 'private, no-store');
    const { session } = await result.json();
    assert.equal(session.provider, 'password');
    assert.equal(JSON.stringify([...admins.values()]).includes(session.token), false);
    assert.ok(Date.parse(session.expiresAt) - Date.now() <= 8 * 3600000);
    assert.equal((await request('/api/admin/session', session.token)).status, 200);
    const site = await createCustomerSession(customer);
    assert.equal((await request('/api/admin/session', site.token)).status, 401);
    assert.equal((await request('/api/customer-auth/session', session.token)).status, 401);
    assert.equal((await fetch(`${base}/api/admin-auth/google`, { method: 'POST' })).status, 404);
    const stored = [...admins.values()][0];
    const expiry = stored.expiresAt; stored.expiresAt = new Date(0);
    assert.equal((await request('/api/admin/session', session.token)).status, 401);
    stored.expiresAt = expiry;
    process.env.ROTAVOY_ADMIN_PASSWORD = 'changed-admin-password';
    assert.equal((await request('/api/admin/session', session.token)).status, 401);
    const second = (await (await login('changed-admin-password')).json()).session;
    assert.equal((await request('/api/admin-auth/logout', second.token, 'POST')).status, 204);
    assert.equal((await request('/api/admin/session', second.token)).status, 401);
    assert.equal((await request('/api/customer-auth/session', site.token)).status, 200);
    assert.equal((await request('/api/customer-auth/logout', site.token, 'POST')).status, 204);
    process.env.ROTAVOY_ADMIN_PASSWORD = 'test-admin-password';
    assert.equal((await request('/api/admin/session', session.token)).status, 200);
    for (let count = 0; count < 6; count++) await login('wrong-password');
    assert.equal((await login('test-admin-password')).status, 429);
  } finally {
    Object.assign(AdminSession, { create: originalAdmin.create, findOne: originalAdmin.find, deleteOne: originalAdmin.remove });
    Object.assign(CustomerSession, { create: originalCustomer.create, findOne: originalCustomer.find, deleteOne: originalCustomer.remove });
    if (previous === undefined) delete process.env.ROTAVOY_ADMIN_PASSWORD; else process.env.ROTAVOY_ADMIN_PASSWORD = previous;
    await new Promise(resolve => server.close(resolve));
  }
});
